// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBww6h3yqc3bW19snHxYfCsEpLcuQNS10',
    appId: '1:837867466538:web:4fe8bc3ef90ac084a6f853',
    messagingSenderId: '837867466538',
    projectId: 'emart-8150b',
    authDomain: 'emart-8150b.firebaseapp.com',
    storageBucket: 'emart-8150b.appspot.com',
    measurementId: 'G-S7PP377LRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCseo6I7AhNsyXotcznXyWnM54pX5Vkf2k',
    appId: '1:837867466538:android:b21c36427e192511a6f853',
    messagingSenderId: '837867466538',
    projectId: 'emart-8150b',
    storageBucket: 'emart-8150b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdptBkgc75OsKaBzMCf2q1zOJwVTZ4a08',
    appId: '1:837867466538:ios:cbd09736bb3040c7a6f853',
    messagingSenderId: '837867466538',
    projectId: 'emart-8150b',
    storageBucket: 'emart-8150b.appspot.com',
    iosBundleId: 'com.ecom.emart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdptBkgc75OsKaBzMCf2q1zOJwVTZ4a08',
    appId: '1:837867466538:ios:42d1c17e2949117da6f853',
    messagingSenderId: '837867466538',
    projectId: 'emart-8150b',
    storageBucket: 'emart-8150b.appspot.com',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBww6h3yqc3bW19snHxYfCsEpLcuQNS10',
    appId: '1:837867466538:web:7e463eb884da2112a6f853',
    messagingSenderId: '837867466538',
    projectId: 'emart-8150b',
    authDomain: 'emart-8150b.firebaseapp.com',
    storageBucket: 'emart-8150b.appspot.com',
    measurementId: 'G-QH7G8Z47S5',
  );
}
